server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      host: 192.168.31.93
      port: 8500
      discovery:
        #        hostname: 192.168.31.93
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
logging:
  level:
    org.apache.zookeeper.ClientCnxn: WARN