server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  cloud:
    zookeeper:
      discovery:
        enabled: true
      connect-string: 192.168.31.93:2181,192.168.31.93:2182,192.168.31.93:2183

logging:
  level:
    org.apache.zookeeper.ClientCnxn: WARN